### PR TITLE
docs: add Node.js native `fetch()` API proxy usage

### PR DESCRIPTION
**Pull request by u3u**

### CODE REVIEW

**Comment by ctjlewis** [comment]
interesting, cc @transmissions11

**Comment by transmissions11** [comment]
i dont see what this has to do with openai-streams lol

**Comment by u3u** [comment]
Because many people cannot use OpenAI without a proxy🙂, the previous version options could not customize "fetch". I just want to share a solution. I don't think everyone knows this.

**Comment by ctjlewis** [comment]
@u3u Sure, not trying to give you a hard time, just haven't seen this many times before. Where have you seen this needed?

**Comment by u3u** [comment]
As far as I know, countries or regions other than the United States, Japan, and Taiwan cannot directly use OpenAI. Even if you can access the API directly, an error message will be prompted.

https://platform.openai.com/docs/supported-countries
https://community.openai.com/search?q=country

**Pull request closed without merging**
